package fpt.edu.vn.sfm.model;
// Generated Sep 14, 2015 8:03:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="smf_test"
)
public class Role  implements java.io.Serializable {


     private Integer roleId;
     private String roleName;
     private Set<SystemUser> systemusers = new HashSet<SystemUser>(0);

    public Role() {
    }

	
    public Role(String roleName) {
        this.roleName = roleName;
    }
    public Role(String roleName, Set<SystemUser> systemusers) {
       this.roleName = roleName;
       this.systemusers = systemusers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RoleID", unique=true, nullable=false)
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="RoleName", nullable=false, length=45)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<SystemUser> getSystemusers() {
        return this.systemusers;
    }
    
    public void setSystemusers(Set<SystemUser> systemusers) {
        this.systemusers = systemusers;
    }




}


