package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="sfm"
)
public class Course  implements java.io.Serializable {


     private Integer courseId;
     private Subject subject;
     private String clazz;
     private int half;
     private Date startDate;
     private Date endDate;
     private String courseStatus;
     private String note;
     private boolean isActive;
     private Set<StudentCourse> studentCourses = new HashSet<StudentCourse>(0);

    public Course() {
    }

	
    public Course(Subject subject, String clazz, int half, String courseStatus, boolean isActive) {
        this.subject = subject;
        this.clazz = clazz;
        this.half = half;
        this.courseStatus = courseStatus;
        this.isActive = isActive;
    }
    public Course(Subject subject, String clazz, int half, Date startDate, Date endDate, String courseStatus, String note, boolean isActive, Set<StudentCourse> studentCourses) {
       this.subject = subject;
       this.clazz = clazz;
       this.half = half;
       this.startDate = startDate;
       this.endDate = endDate;
       this.courseStatus = courseStatus;
       this.note = note;
       this.isActive = isActive;
       this.studentCourses = studentCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CourseID", unique=true, nullable=false)
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubjectID", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    
    @Column(name="Clazz", nullable=false, length=30)
    public String getClazz() {
        return this.clazz;
    }
    
    public void setClazz(String clazz) {
        this.clazz = clazz;
    }

    
    @Column(name="Half", nullable=false)
    public int getHalf() {
        return this.half;
    }
    
    public void setHalf(int half) {
        this.half = half;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartDate", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndDate", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="CourseStatus", nullable=false, length=30)
    public String getCourseStatus() {
        return this.courseStatus;
    }
    
    public void setCourseStatus(String courseStatus) {
        this.courseStatus = courseStatus;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<StudentCourse> getStudentCourses() {
        return this.studentCourses;
    }
    
    public void setStudentCourses(Set<StudentCourse> studentCourses) {
        this.studentCourses = studentCourses;
    }




}


