package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CreditStudent generated by hbm2java
 */
@Entity
@Table(name="credit_student"
    ,catalog="sfm"
)
public class CreditStudent  implements java.io.Serializable {


     private Integer studentId;
     private Student student;
     private int creditRate;
     private Set<CreditDebt> creditDebts = new HashSet<CreditDebt>(0);

    public CreditStudent() {
    }

	
    public CreditStudent(Student student, int creditRate) {
        this.student = student;
        this.creditRate = creditRate;
    }
    public CreditStudent(Student student, int creditRate, Set<CreditDebt> creditDebts) {
       this.student = student;
       this.creditRate = creditRate;
       this.creditDebts = creditDebts;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="StudentID", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="CreditRate", nullable=false)
    public int getCreditRate() {
        return this.creditRate;
    }
    
    public void setCreditRate(int creditRate) {
        this.creditRate = creditRate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="creditStudent")
    public Set<CreditDebt> getCreditDebts() {
        return this.creditDebts;
    }
    
    public void setCreditDebts(Set<CreditDebt> creditDebts) {
        this.creditDebts = creditDebts;
    }




}


