package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * InvestingStudent generated by hbm2java
 */
@Entity
@Table(name="investing_student"
    ,catalog="sfm"
)
public class InvestingStudent  implements java.io.Serializable {


     private int studentId;
     private Student student;
     private int investingRate;
     private Set<InvestingReport> investingReports = new HashSet<InvestingReport>(0);

    public InvestingStudent() {
    }

	
    public InvestingStudent(Student student, int investingRate) {
        this.student = student;
        this.investingRate = investingRate;
    }
    public InvestingStudent(Student student, int investingRate, Set<InvestingReport> investingReports) {
       this.student = student;
       this.investingRate = investingRate;
       this.investingReports = investingReports;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="StudentID", unique=true, nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="InvestingRate", nullable=false)
    public int getInvestingRate() {
        return this.investingRate;
    }
    
    public void setInvestingRate(int investingRate) {
        this.investingRate = investingRate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investingStudent")
    public Set<InvestingReport> getInvestingReports() {
        return this.investingReports;
    }
    
    public void setInvestingReports(Set<InvestingReport> investingReports) {
        this.investingReports = investingReports;
    }




}


