package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvestingReport generated by hbm2java
 */
@Entity
@Table(name="investing_report"
    ,catalog="sfm"
)
public class InvestingReport  implements java.io.Serializable {


     private Integer reportId;
     private InvestingStudent investingStudent;
     private String totalMoney;
     private String paidMoney;
     private boolean payStatus;
     private String bank;
     private Date dateTransfer;

    public InvestingReport() {
    }

	
    public InvestingReport(InvestingStudent investingStudent, String totalMoney, String paidMoney, boolean payStatus) {
        this.investingStudent = investingStudent;
        this.totalMoney = totalMoney;
        this.paidMoney = paidMoney;
        this.payStatus = payStatus;
    }
    public InvestingReport(InvestingStudent investingStudent, String totalMoney, String paidMoney, boolean payStatus, String bank, Date dateTransfer) {
       this.investingStudent = investingStudent;
       this.totalMoney = totalMoney;
       this.paidMoney = paidMoney;
       this.payStatus = payStatus;
       this.bank = bank;
       this.dateTransfer = dateTransfer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ReportID", unique=true, nullable=false)
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public InvestingStudent getInvestingStudent() {
        return this.investingStudent;
    }
    
    public void setInvestingStudent(InvestingStudent investingStudent) {
        this.investingStudent = investingStudent;
    }

    
    @Column(name="TotalMoney", nullable=false, length=16777215)
    public String getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(String totalMoney) {
        this.totalMoney = totalMoney;
    }

    
    @Column(name="PaidMoney", nullable=false, length=16777215)
    public String getPaidMoney() {
        return this.paidMoney;
    }
    
    public void setPaidMoney(String paidMoney) {
        this.paidMoney = paidMoney;
    }

    
    @Column(name="PayStatus", nullable=false)
    public boolean isPayStatus() {
        return this.payStatus;
    }
    
    public void setPayStatus(boolean payStatus) {
        this.payStatus = payStatus;
    }

    
    @Column(name="Bank", length=45)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateTransfer", length=19)
    public Date getDateTransfer() {
        return this.dateTransfer;
    }
    
    public void setDateTransfer(Date dateTransfer) {
        this.dateTransfer = dateTransfer;
    }




}


