package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LoansStudent generated by hbm2java
 */
@Entity
@Table(name="loans_student"
    ,catalog="sfm"
)
public class LoansStudent  implements java.io.Serializable {


     private Integer studentId;
     private Student student;
     private int loansRate;
     private Set<LoansInterest> loansInterests = new HashSet<LoansInterest>(0);

    public LoansStudent() {
    }

	
    public LoansStudent(Student student, int loansRate) {
        this.student = student;
        this.loansRate = loansRate;
    }
    public LoansStudent(Student student, int loansRate, Set<LoansInterest> loansInterests) {
       this.student = student;
       this.loansRate = loansRate;
       this.loansInterests = loansInterests;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="StudentID", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="LoansRate", nullable=false)
    public int getLoansRate() {
        return this.loansRate;
    }
    
    public void setLoansRate(int loansRate) {
        this.loansRate = loansRate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loansStudent")
    public Set<LoansInterest> getLoansInterests() {
        return this.loansInterests;
    }
    
    public void setLoansInterests(Set<LoansInterest> loansInterests) {
        this.loansInterests = loansInterests;
    }




}


