package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LoansInterest generated by hbm2java
 */
@Entity
@Table(name="loans_interest"
    ,catalog="sfm"
)
public class LoansInterest  implements java.io.Serializable {


     private Integer reportId;
     private LoansStudent loansStudent;
     private Integer interestRate;
     private String baseMoney;
     private String interest;
     private String totalInterest;
     private String note;
     private boolean isActive;

    public LoansInterest() {
    }

	
    public LoansInterest(LoansStudent loansStudent, String baseMoney, String interest, String totalInterest, boolean isActive) {
        this.loansStudent = loansStudent;
        this.baseMoney = baseMoney;
        this.interest = interest;
        this.totalInterest = totalInterest;
        this.isActive = isActive;
    }
    public LoansInterest(LoansStudent loansStudent, Integer interestRate, String baseMoney, String interest, String totalInterest, String note, boolean isActive) {
       this.loansStudent = loansStudent;
       this.interestRate = interestRate;
       this.baseMoney = baseMoney;
       this.interest = interest;
       this.totalInterest = totalInterest;
       this.note = note;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ReportID", unique=true, nullable=false)
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public LoansStudent getLoansStudent() {
        return this.loansStudent;
    }
    
    public void setLoansStudent(LoansStudent loansStudent) {
        this.loansStudent = loansStudent;
    }

    
    @Column(name="InterestRate")
    public Integer getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(Integer interestRate) {
        this.interestRate = interestRate;
    }

    
    @Column(name="BaseMoney", nullable=false, length=16777215)
    public String getBaseMoney() {
        return this.baseMoney;
    }
    
    public void setBaseMoney(String baseMoney) {
        this.baseMoney = baseMoney;
    }

    
    @Column(name="Interest", nullable=false, length=16777215)
    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }

    
    @Column(name="TotalInterest", nullable=false, length=16777215)
    public String getTotalInterest() {
        return this.totalInterest;
    }
    
    public void setTotalInterest(String totalInterest) {
        this.totalInterest = totalInterest;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


