package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name="major"
    ,catalog="sfm"
)
public class Major  implements java.io.Serializable {


     private Integer majorId;
     private String majorCode;
     private String majorName;
     private String note;
     private boolean isActive;
     private Set<Student> students = new HashSet<Student>(0);
     private Set<SubjectInLevel> subjectInLevels = new HashSet<SubjectInLevel>(0);

    public Major() {
    }

	
    public Major(String majorCode, String majorName, boolean isActive) {
        this.majorCode = majorCode;
        this.majorName = majorName;
        this.isActive = isActive;
    }
    public Major(String majorCode, String majorName, String note, boolean isActive, Set<Student> students, Set<SubjectInLevel> subjectInLevels) {
       this.majorCode = majorCode;
       this.majorName = majorName;
       this.note = note;
       this.isActive = isActive;
       this.students = students;
       this.subjectInLevels = subjectInLevels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MajorID", unique=true, nullable=false)
    public Integer getMajorId() {
        return this.majorId;
    }
    
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    
    @Column(name="MajorCode", nullable=false, length=10)
    public String getMajorCode() {
        return this.majorCode;
    }
    
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode;
    }

    
    @Column(name="MajorName", nullable=false, length=45)
    public String getMajorName() {
        return this.majorName;
    }
    
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="major")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="major")
    public Set<SubjectInLevel> getSubjectInLevels() {
        return this.subjectInLevels;
    }
    
    public void setSubjectInLevels(Set<SubjectInLevel> subjectInLevels) {
        this.subjectInLevels = subjectInLevels;
    }




}


