package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 1:43:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MandatorySubject generated by hbm2java
 */
@Entity
@Table(name="mandatory_subject"
    ,catalog="sfm"
)
public class MandatorySubject  implements java.io.Serializable {


     private MandatorySubjectId id;
     private Subject subjectByMandatorySubjectId;
     private Subject subjectBySubjectId;
     private String note;
     private Boolean isActive;
     private Date dateCreated;
     private Date dateUpdated;

    public MandatorySubject() {
    }

	
    public MandatorySubject(MandatorySubjectId id, Subject subjectByMandatorySubjectId, Subject subjectBySubjectId) {
        this.id = id;
        this.subjectByMandatorySubjectId = subjectByMandatorySubjectId;
        this.subjectBySubjectId = subjectBySubjectId;
    }
    public MandatorySubject(MandatorySubjectId id, Subject subjectByMandatorySubjectId, Subject subjectBySubjectId, String note, Boolean isActive, Date dateCreated, Date dateUpdated) {
       this.id = id;
       this.subjectByMandatorySubjectId = subjectByMandatorySubjectId;
       this.subjectBySubjectId = subjectBySubjectId;
       this.note = note;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="subjectId", column=@Column(name="SubjectId", nullable=false) ), 
        @AttributeOverride(name="mandatorySubjectId", column=@Column(name="MandatorySubjectID", nullable=false) ) } )
    public MandatorySubjectId getId() {
        return this.id;
    }
    
    public void setId(MandatorySubjectId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MandatorySubjectID", nullable=false, insertable=false, updatable=false)
    public Subject getSubjectByMandatorySubjectId() {
        return this.subjectByMandatorySubjectId;
    }
    
    public void setSubjectByMandatorySubjectId(Subject subjectByMandatorySubjectId) {
        this.subjectByMandatorySubjectId = subjectByMandatorySubjectId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubjectId", nullable=false, insertable=false, updatable=false)
    public Subject getSubjectBySubjectId() {
        return this.subjectBySubjectId;
    }
    
    public void setSubjectBySubjectId(Subject subjectBySubjectId) {
        this.subjectBySubjectId = subjectBySubjectId;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


