package com.project.fpt.sfm.entities;
// Generated Oct 12, 2015 1:43:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MandatorySubjectId generated by hbm2java
 */
@Embeddable
public class MandatorySubjectId  implements java.io.Serializable {


     private int subjectId;
     private int mandatorySubjectId;

    public MandatorySubjectId() {
    }

    public MandatorySubjectId(int subjectId, int mandatorySubjectId) {
       this.subjectId = subjectId;
       this.mandatorySubjectId = mandatorySubjectId;
    }
   


    @Column(name="SubjectId", nullable=false)
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }


    @Column(name="MandatorySubjectID", nullable=false)
    public int getMandatorySubjectId() {
        return this.mandatorySubjectId;
    }
    
    public void setMandatorySubjectId(int mandatorySubjectId) {
        this.mandatorySubjectId = mandatorySubjectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MandatorySubjectId) ) return false;
		 MandatorySubjectId castOther = ( MandatorySubjectId ) other; 
         
		 return (this.getSubjectId()==castOther.getSubjectId())
 && (this.getMandatorySubjectId()==castOther.getMandatorySubjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSubjectId();
         result = 37 * result + this.getMandatorySubjectId();
         return result;
   }   


}


