package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paidamount generated by hbm2java
 */
@Entity
@Table(name="paidamount"
    ,catalog="sfm"
)
public class Paidamount  implements java.io.Serializable {


     private Integer paidAmountId;
     private String paidAmount;
     private Set<SessionTuition> sessionTuitions = new HashSet<SessionTuition>(0);

    public Paidamount() {
    }

    public Paidamount(String paidAmount, Set<SessionTuition> sessionTuitions) {
       this.paidAmount = paidAmount;
       this.sessionTuitions = sessionTuitions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PaidAmountID", unique=true, nullable=false)
    public Integer getPaidAmountId() {
        return this.paidAmountId;
    }
    
    public void setPaidAmountId(Integer paidAmountId) {
        this.paidAmountId = paidAmountId;
    }

    
    @Column(name="PaidAmount", length=16777215)
    public String getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(String paidAmount) {
        this.paidAmount = paidAmount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paidamount")
    public Set<SessionTuition> getSessionTuitions() {
        return this.sessionTuitions;
    }
    
    public void setSessionTuitions(Set<SessionTuition> sessionTuitions) {
        this.sessionTuitions = sessionTuitions;
    }




}


