package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResitCoursePayment generated by hbm2java
 */
@Entity
@Table(name="resit_course_payment"
    ,catalog="sfm"
)
public class ResitCoursePayment  implements java.io.Serializable {


     private Integer resitCoursePaymentId;
     private Student student;
     private StudentCourse studentCourse;
     private int totalTuition;
     private int paidAmount;
     private boolean status;
     private Date transferDate;
     private String note;
     private int attempt;
     private boolean isActive;

    public ResitCoursePayment() {
    }

	
    public ResitCoursePayment(Student student, StudentCourse studentCourse, int totalTuition, int paidAmount, boolean status, int attempt, boolean isActive) {
        this.student = student;
        this.studentCourse = studentCourse;
        this.totalTuition = totalTuition;
        this.paidAmount = paidAmount;
        this.status = status;
        this.attempt = attempt;
        this.isActive = isActive;
    }
    public ResitCoursePayment(Student student, StudentCourse studentCourse, int totalTuition, int paidAmount, boolean status, Date transferDate, String note, int attempt, boolean isActive) {
       this.student = student;
       this.studentCourse = studentCourse;
       this.totalTuition = totalTuition;
       this.paidAmount = paidAmount;
       this.status = status;
       this.transferDate = transferDate;
       this.note = note;
       this.attempt = attempt;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ResitCoursePaymentID", unique=true, nullable=false)
    public Integer getResitCoursePaymentId() {
        return this.resitCoursePaymentId;
    }
    
    public void setResitCoursePaymentId(Integer resitCoursePaymentId) {
        this.resitCoursePaymentId = resitCoursePaymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentCourseID", nullable=false)
    public StudentCourse getStudentCourse() {
        return this.studentCourse;
    }
    
    public void setStudentCourse(StudentCourse studentCourse) {
        this.studentCourse = studentCourse;
    }

    
    @Column(name="TotalTuition", nullable=false)
    public int getTotalTuition() {
        return this.totalTuition;
    }
    
    public void setTotalTuition(int totalTuition) {
        this.totalTuition = totalTuition;
    }

    
    @Column(name="PaidAmount", nullable=false)
    public int getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(int paidAmount) {
        this.paidAmount = paidAmount;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransferDate", length=19)
    public Date getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="Attempt", nullable=false)
    public int getAttempt() {
        return this.attempt;
    }
    
    public void setAttempt(int attempt) {
        this.attempt = attempt;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


