package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ScholarshipStudent generated by hbm2java
 */
@Entity
@Table(name="scholarship_student"
    ,catalog="sfm"
)
public class ScholarshipStudent  implements java.io.Serializable {


     private int studentId;
     private Student student;
     private int scholarshipRate;

    public ScholarshipStudent() {
    }

    public ScholarshipStudent(Student student, int scholarshipRate) {
       this.student = student;
       this.scholarshipRate = scholarshipRate;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="StudentID", unique=true, nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="ScholarshipRate", nullable=false)
    public int getScholarshipRate() {
        return this.scholarshipRate;
    }
    
    public void setScholarshipRate(int scholarshipRate) {
        this.scholarshipRate = scholarshipRate;
    }




}


