package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Season generated by hbm2java
 */
@Entity
@Table(name="season"
    ,catalog="sfm"
)
public class Season  implements java.io.Serializable {


     private Integer seasonId;
     private String seasonName;
     private Date startDate;
     private Date endDate;
     private String note;
     private String isActive;
     private Set<Semester> semesters = new HashSet<Semester>(0);

    public Season() {
    }

	
    public Season(String seasonName, String isActive) {
        this.seasonName = seasonName;
        this.isActive = isActive;
    }
    public Season(String seasonName, Date startDate, Date endDate, String note, String isActive, Set<Semester> semesters) {
       this.seasonName = seasonName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.note = note;
       this.isActive = isActive;
       this.semesters = semesters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SeasonID", unique=true, nullable=false)
    public Integer getSeasonId() {
        return this.seasonId;
    }
    
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    
    @Column(name="SeasonName", nullable=false, length=45)
    public String getSeasonName() {
        return this.seasonName;
    }
    
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartDate", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndDate", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false, length=45)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="season")
    public Set<Semester> getSemesters() {
        return this.semesters;
    }
    
    public void setSemesters(Set<Semester> semesters) {
        this.semesters = semesters;
    }




}


