package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semester generated by hbm2java
 */
@Entity
@Table(name="semester"
    ,catalog="sfm"
)
public class Semester  implements java.io.Serializable {


     private Integer semesterId;
     private Season season;
     private Student student;
     private StudyLevel studyLevel;
     private Set<TuitionPayment> tuitionPayments = new HashSet<TuitionPayment>(0);
     private Set<StudentCourse> studentCourses = new HashSet<StudentCourse>(0);

    public Semester() {
    }

	
    public Semester(Season season, Student student, StudyLevel studyLevel) {
        this.season = season;
        this.student = student;
        this.studyLevel = studyLevel;
    }
    public Semester(Season season, Student student, StudyLevel studyLevel, Set<TuitionPayment> tuitionPayments, Set<StudentCourse> studentCourses) {
       this.season = season;
       this.student = student;
       this.studyLevel = studyLevel;
       this.tuitionPayments = tuitionPayments;
       this.studentCourses = studentCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SemesterID", unique=true, nullable=false)
    public Integer getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SeasonID", nullable=false)
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudyLevelID", nullable=false)
    public StudyLevel getStudyLevel() {
        return this.studyLevel;
    }
    
    public void setStudyLevel(StudyLevel studyLevel) {
        this.studyLevel = studyLevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semester")
    public Set<TuitionPayment> getTuitionPayments() {
        return this.tuitionPayments;
    }
    
    public void setTuitionPayments(Set<TuitionPayment> tuitionPayments) {
        this.tuitionPayments = tuitionPayments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semester")
    public Set<StudentCourse> getStudentCourses() {
        return this.studentCourses;
    }
    
    public void setStudentCourses(Set<StudentCourse> studentCourses) {
        this.studentCourses = studentCourses;
    }




}


