package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semester generated by hbm2java
 */
@Entity
@Table(name="semester"
    ,catalog="sfm"
)
public class Semester  implements java.io.Serializable {


     private Integer semesterId;
     private String semesterName;
     private Date startDate;
     private Date endDate;
     private String note;
     private boolean isActive;
     private Set<StudySession> studySessions = new HashSet<StudySession>(0);

    public Semester() {
    }

	
    public Semester(String semesterName, Date startDate, Date endDate, boolean isActive) {
        this.semesterName = semesterName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.isActive = isActive;
    }
    public Semester(String semesterName, Date startDate, Date endDate, String note, boolean isActive, Set<StudySession> studySessions) {
       this.semesterName = semesterName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.note = note;
       this.isActive = isActive;
       this.studySessions = studySessions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SemesterID", unique=true, nullable=false)
    public Integer getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }

    
    @Column(name="SemesterName", nullable=false, length=45)
    public String getSemesterName() {
        return this.semesterName;
    }
    
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartDate", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndDate", nullable=false, length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semester")
    public Set<StudySession> getStudySessions() {
        return this.studySessions;
    }
    
    public void setStudySessions(Set<StudySession> studySessions) {
        this.studySessions = studySessions;
    }




}


