package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SessionTuition generated by hbm2java
 */
@Entity
@Table(name="session_tuition"
    ,catalog="sfm"
)
public class SessionTuition  implements java.io.Serializable {


     private Integer sessionId;
     private StudySession studySession;
     private String totalMoney;
     private String subtractMoney;
     private String realPayMoney;
     private String paidMoney;
     private String bank;
     private Date transferDate;
     private boolean isPaidFull;
     private String note;
     private boolean isActive;

    public SessionTuition() {
    }

	
    public SessionTuition(StudySession studySession, String totalMoney, String subtractMoney, String realPayMoney, String paidMoney, boolean isPaidFull, boolean isActive) {
        this.studySession = studySession;
        this.totalMoney = totalMoney;
        this.subtractMoney = subtractMoney;
        this.realPayMoney = realPayMoney;
        this.paidMoney = paidMoney;
        this.isPaidFull = isPaidFull;
        this.isActive = isActive;
    }
    public SessionTuition(StudySession studySession, String totalMoney, String subtractMoney, String realPayMoney, String paidMoney, String bank, Date transferDate, boolean isPaidFull, String note, boolean isActive) {
       this.studySession = studySession;
       this.totalMoney = totalMoney;
       this.subtractMoney = subtractMoney;
       this.realPayMoney = realPayMoney;
       this.paidMoney = paidMoney;
       this.bank = bank;
       this.transferDate = transferDate;
       this.isPaidFull = isPaidFull;
       this.note = note;
       this.isActive = isActive;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="studySession"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="SessionID", unique=true, nullable=false)
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public StudySession getStudySession() {
        return this.studySession;
    }
    
    public void setStudySession(StudySession studySession) {
        this.studySession = studySession;
    }

    
    @Column(name="TotalMoney", nullable=false, length=16777215)
    public String getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(String totalMoney) {
        this.totalMoney = totalMoney;
    }

    
    @Column(name="SubtractMoney", nullable=false, length=16777215)
    public String getSubtractMoney() {
        return this.subtractMoney;
    }
    
    public void setSubtractMoney(String subtractMoney) {
        this.subtractMoney = subtractMoney;
    }

    
    @Column(name="RealPayMoney", nullable=false, length=16777215)
    public String getRealPayMoney() {
        return this.realPayMoney;
    }
    
    public void setRealPayMoney(String realPayMoney) {
        this.realPayMoney = realPayMoney;
    }

    
    @Column(name="PaidMoney", nullable=false, length=16777215)
    public String getPaidMoney() {
        return this.paidMoney;
    }
    
    public void setPaidMoney(String paidMoney) {
        this.paidMoney = paidMoney;
    }

    
    @Column(name="Bank", length=45)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransferDate", length=19)
    public Date getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }

    
    @Column(name="IsPaidFull", nullable=false)
    public boolean isIsPaidFull() {
        return this.isPaidFull;
    }
    
    public void setIsPaidFull(boolean isPaidFull) {
        this.isPaidFull = isPaidFull;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


