package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SessionTuition generated by hbm2java
 */
@Entity
@Table(name="session_tuition"
    ,catalog="sfm"
)
public class SessionTuition  implements java.io.Serializable {


     private Integer sessionId;
     private Paidamount paidamount;
     private StudySession studySession;
     private Subtractamount subtractamount;
     private String totalMoney;
     private String realPayMoney;
     private String bank;
     private Date transferDate;
     private boolean isPaidFull;
     private String note;
     private boolean isActive;

    public SessionTuition() {
    }

	
    public SessionTuition(Paidamount paidamount, StudySession studySession, Subtractamount subtractamount, String totalMoney, String realPayMoney, boolean isPaidFull, boolean isActive) {
        this.paidamount = paidamount;
        this.studySession = studySession;
        this.subtractamount = subtractamount;
        this.totalMoney = totalMoney;
        this.realPayMoney = realPayMoney;
        this.isPaidFull = isPaidFull;
        this.isActive = isActive;
    }
    public SessionTuition(Paidamount paidamount, StudySession studySession, Subtractamount subtractamount, String totalMoney, String realPayMoney, String bank, Date transferDate, boolean isPaidFull, String note, boolean isActive) {
       this.paidamount = paidamount;
       this.studySession = studySession;
       this.subtractamount = subtractamount;
       this.totalMoney = totalMoney;
       this.realPayMoney = realPayMoney;
       this.bank = bank;
       this.transferDate = transferDate;
       this.isPaidFull = isPaidFull;
       this.note = note;
       this.isActive = isActive;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="studySession"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="SessionID", unique=true, nullable=false)
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PaidMoneyID", nullable=false)
    public Paidamount getPaidamount() {
        return this.paidamount;
    }
    
    public void setPaidamount(Paidamount paidamount) {
        this.paidamount = paidamount;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public StudySession getStudySession() {
        return this.studySession;
    }
    
    public void setStudySession(StudySession studySession) {
        this.studySession = studySession;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubtractAmountID", nullable=false)
    public Subtractamount getSubtractamount() {
        return this.subtractamount;
    }
    
    public void setSubtractamount(Subtractamount subtractamount) {
        this.subtractamount = subtractamount;
    }

    
    @Column(name="TotalMoney", nullable=false, length=16777215)
    public String getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(String totalMoney) {
        this.totalMoney = totalMoney;
    }

    
    @Column(name="RealPayMoney", nullable=false, length=16777215)
    public String getRealPayMoney() {
        return this.realPayMoney;
    }
    
    public void setRealPayMoney(String realPayMoney) {
        this.realPayMoney = realPayMoney;
    }

    
    @Column(name="Bank", length=45)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransferDate", length=19)
    public Date getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }

    
    @Column(name="IsPaidFull", nullable=false)
    public boolean isIsPaidFull() {
        return this.isPaidFull;
    }
    
    public void setIsPaidFull(boolean isPaidFull) {
        this.isPaidFull = isPaidFull;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


