package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name="session"
    ,catalog="sfm"
)
public class Session  implements java.io.Serializable {


     private Integer sessionId;
     private String sessionCode;
     private String progressName;
     private String tuitionUsa;
     private String tuitionVnd;
     private String note;
     private Boolean isActive;
     private Set<StudySession> studySessions = new HashSet<StudySession>(0);

    public Session() {
    }

    public Session(String sessionCode, String progressName, String tuitionUsa, String tuitionVnd, String note, Boolean isActive, Set<StudySession> studySessions) {
       this.sessionCode = sessionCode;
       this.progressName = progressName;
       this.tuitionUsa = tuitionUsa;
       this.tuitionVnd = tuitionVnd;
       this.note = note;
       this.isActive = isActive;
       this.studySessions = studySessions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SessionID", unique=true, nullable=false)
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    
    @Column(name="SessionCode", length=15)
    public String getSessionCode() {
        return this.sessionCode;
    }
    
    public void setSessionCode(String sessionCode) {
        this.sessionCode = sessionCode;
    }

    
    @Column(name="ProgressName", length=45)
    public String getProgressName() {
        return this.progressName;
    }
    
    public void setProgressName(String progressName) {
        this.progressName = progressName;
    }

    
    @Column(name="TuitionUSA", length=16777215)
    public String getTuitionUsa() {
        return this.tuitionUsa;
    }
    
    public void setTuitionUsa(String tuitionUsa) {
        this.tuitionUsa = tuitionUsa;
    }

    
    @Column(name="TuitionVND", length=16777215)
    public String getTuitionVnd() {
        return this.tuitionVnd;
    }
    
    public void setTuitionVnd(String tuitionVnd) {
        this.tuitionVnd = tuitionVnd;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="session")
    public Set<StudySession> getStudySessions() {
        return this.studySessions;
    }
    
    public void setStudySessions(Set<StudySession> studySessions) {
        this.studySessions = studySessions;
    }




}


