package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * StudySession generated by hbm2java
 */
@Entity
@Table(name="study_session"
    ,catalog="sfm"
)
public class StudySession  implements java.io.Serializable {


     private int studySessionId;
     private Semester semester;
     private Session session;
     private Student student;
     private SessionTuition sessionTuition;
     private Set<StudentCourse> studentCourses = new HashSet<StudentCourse>(0);

    public StudySession() {
    }

	
    public StudySession(int studySessionId, Semester semester, Session session, Student student) {
        this.studySessionId = studySessionId;
        this.semester = semester;
        this.session = session;
        this.student = student;
    }
    public StudySession(int studySessionId, Semester semester, Session session, Student student, SessionTuition sessionTuition, Set<StudentCourse> studentCourses) {
       this.studySessionId = studySessionId;
       this.semester = semester;
       this.session = session;
       this.student = student;
       this.sessionTuition = sessionTuition;
       this.studentCourses = studentCourses;
    }
   
     @Id 

    
    @Column(name="StudySessionID", unique=true, nullable=false)
    public int getStudySessionId() {
        return this.studySessionId;
    }
    
    public void setStudySessionId(int studySessionId) {
        this.studySessionId = studySessionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SemesterID", nullable=false)
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SessionID", nullable=false)
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="studySession")
    public SessionTuition getSessionTuition() {
        return this.sessionTuition;
    }
    
    public void setSessionTuition(SessionTuition sessionTuition) {
        this.sessionTuition = sessionTuition;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studySession")
    public Set<StudentCourse> getStudentCourses() {
        return this.studentCourses;
    }
    
    public void setStudentCourses(Set<StudentCourse> studentCourses) {
        this.studentCourses = studentCourses;
    }




}


