package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentCourse generated by hbm2java
 */
@Entity
@Table(name="student_course"
    ,catalog="sfm"
)
public class StudentCourse  implements java.io.Serializable {


     private Integer studentCourseId;
     private Course course;
     private Semester semester;
     private Student student;
     private float mark;
     private boolean isPass;
     private boolean isActive;
    private boolean isResit;
     private String note;
     private Set<ResitCoursePayment> resitCoursePayments = new HashSet<ResitCoursePayment>(0);

    public StudentCourse() {
    }

	
    public StudentCourse(Course course, Semester semester, Student student, float mark, boolean isPass, boolean isActive) {
        this.course = course;
        this.semester = semester;
        this.student = student;
        this.mark = mark;
        this.isPass = isPass;
        this.isActive = isActive;
    }
    public StudentCourse(Course course, Semester semester, Student student, float mark, boolean isPass, boolean isActive, String note, Set<ResitCoursePayment> resitCoursePayments) {
       this.course = course;
       this.semester = semester;
       this.student = student;
       this.mark = mark;
       this.isPass = isPass;
       this.isActive = isActive;
       this.note = note;
       this.resitCoursePayments = resitCoursePayments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="StudentCourseID", unique=true, nullable=false)
    public Integer getStudentCourseId() {
        return this.studentCourseId;
    }
    
    public void setStudentCourseId(Integer studentCourseId) {
        this.studentCourseId = studentCourseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CourseID", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SemesterID", nullable=false)
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="Mark", nullable=false, precision=12, scale=0)
    public float getMark() {
        return this.mark;
    }
    
    public void setMark(float mark) {
        this.mark = mark;
    }

    
    @Column(name="IsPass", nullable=false)
    public boolean isIsPass() {
        return this.isPass;
    }
    
    public void setIsPass(boolean isPass) {
        this.isPass = isPass;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Column(name="IsResit", nullable=false)
    public boolean isIsResit() {
        return this.isResit;
    }

    public void setIsResit(boolean isResit) {
        this.isResit = isResit;
    }


    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentCourse")
    public Set<ResitCoursePayment> getResitCoursePayments() {
        return this.resitCoursePayments;
    }
    
    public void setResitCoursePayments(Set<ResitCoursePayment> resitCoursePayments) {
        this.resitCoursePayments = resitCoursePayments;
    }




}


