package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.project.fpt.sfm.common.ExcelColumn;
import com.project.fpt.sfm.common.ExcelReport;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="sfm"
    , uniqueConstraints = @UniqueConstraint(columnNames="StudentCode") 
)
@ExcelReport(documentName = "StudentInformation", sheetName = "BasicInformation")
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private User user;
     private String major;
     private String studyStatus;
     private String term;
     private String special;
     private String fullName;
     private Date dateOfBirth;
     private String email;
     private String studentCode;
     private Boolean gender;
     private String parentPhone;
     private String parentEmail;
     private Boolean isGraduated;
     private String ssn;
     private String phoneNumber;
     private String address;
     private String class_;
     private ScholarshipStudent scholarshipStudent;
     private InvestingStudent investingStudent;
     private Set<StudySession> studySessions = new HashSet<StudySession>(0);
     private LoansStudent loansStudent;

    public Student() {
    }

	
    public Student(User user) {
        this.user = user;
    }
    public Student(User user, String major, String studyStatus, String term, String special, String fullName, Date dateOfBirth, String email, String studentCode, Boolean gender, String parentPhone, String parentEmail, Boolean isGraduated, String ssn, String phoneNumber, String address, String class_, ScholarshipStudent scholarshipStudent, InvestingStudent investingStudent, Set<StudySession> studySessions, LoansStudent loansStudent) {
       this.user = user;
       this.major = major;
       this.studyStatus = studyStatus;
       this.term = term;
       this.special = special;
       this.fullName = fullName;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.studentCode = studentCode;
       this.gender = gender;
       this.parentPhone = parentPhone;
       this.parentEmail = parentEmail;
       this.isGraduated = isGraduated;
       this.ssn = ssn;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.class_ = class_;
       this.scholarshipStudent = scholarshipStudent;
       this.investingStudent = investingStudent;
       this.studySessions = studySessions;
       this.loansStudent = loansStudent;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="user"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="StudentID", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }


    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Major", length=10)
    @ExcelColumn(label = "Chuyên Ngành", order = 13)
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }

    
    @Column(name="StudyStatus", length=30)
    @ExcelColumn(label = "Trạng Thái", order = 14)
    public String getStudyStatus() {
        return this.studyStatus;
    }
    
    public void setStudyStatus(String studyStatus) {
        this.studyStatus = studyStatus;
    }

    
    @Column(name="Term", length=10)
    @ExcelColumn(label = "Khóa", order = 15)
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }

    
    @Column(name="Special", length=10)
    @ExcelColumn(label = "Chuyên Ngành Hẹp", order = 7)
    public String getSpecial() {
        return this.special;
    }
    
    public void setSpecial(String special) {
        this.special = special;
    }

    
    @Column(name="FullName", length=64)
    @ExcelColumn(label = "Họ & Tên", order = 2)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateOfBirth", length=19)
    @ExcelColumn(label = "Ngày Sinh", order = 4)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="Email")
    @ExcelColumn(label = "Email", order = 6)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="StudentCode", unique=true, length=10)
    @ExcelColumn(label = "MSSV", order = 1)
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    
    @Column(name="Gender")
    @ExcelColumn(label = "Giới Tính", order = 3)
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    
    @Column(name="ParentPhone", length=15)
    @ExcelColumn(label = "Số Điện Thoại Phụ Huynh", order = 9)
    public String getParentPhone() {
        return this.parentPhone;
    }
    
    public void setParentPhone(String parentPhone) {
        this.parentPhone = parentPhone;
    }

    
    @Column(name="ParentEmail")
    @ExcelColumn(label = "Email Phụ Huynh", order = 10)
    public String getParentEmail() {
        return this.parentEmail;
    }
    
    public void setParentEmail(String parentEmail) {
        this.parentEmail = parentEmail;
    }

    
    @Column(name="IsGraduated")
    @ExcelColumn(label = "Trạng Thái Tốt Nghiệp", order = 11)
    public Boolean getIsGraduated() {
        return this.isGraduated;
    }
    
    public void setIsGraduated(Boolean isGraduated) {
        this.isGraduated = isGraduated;
    }

    
    @Column(name="SSN", length=10)
    @ExcelColumn(label = "CMND", order = 12)
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    
    @Column(name="PhoneNumber", length=15)
    @ExcelColumn(label = "Điện Thoại", order = 5)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Address", length=65535)
    @ExcelColumn(label = "Địa Chỉ", order = 8)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="class", length=15)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="student")
    public ScholarshipStudent getScholarshipStudent() {
        return this.scholarshipStudent;
    }
    
    public void setScholarshipStudent(ScholarshipStudent scholarshipStudent) {
        this.scholarshipStudent = scholarshipStudent;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="student")
    public InvestingStudent getInvestingStudent() {
        return this.investingStudent;
    }
    
    public void setInvestingStudent(InvestingStudent investingStudent) {
        this.investingStudent = investingStudent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<StudySession> getStudySessions() {
        return this.studySessions;
    }
    
    public void setStudySessions(Set<StudySession> studySessions) {
        this.studySessions = studySessions;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="student")
    public LoansStudent getLoansStudent() {
        return this.loansStudent;
    }
    
    public void setLoansStudent(LoansStudent loansStudent) {
        this.loansStudent = loansStudent;
    }




}


