package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * StudentCourse generated by hbm2java
 */
@Entity
@Table(name="student_course"
    ,catalog="sfm"
)
public class StudentCourse  implements java.io.Serializable {


     private Integer studentCourseId;
     private Course course;
     private StudySession studySession;
     private String studyMode;
     private Boolean isPass;
     private float mark;
     private String note;
     private boolean isActive;
     private StudentResitCourse studentResitCourse;

    public StudentCourse() {
    }

	
    public StudentCourse(float mark, boolean isActive) {
        this.mark = mark;
        this.isActive = isActive;
    }
    public StudentCourse(Course course, StudySession studySession, String studyMode, Boolean isPass, float mark, String note, boolean isActive, StudentResitCourse studentResitCourse) {
       this.course = course;
       this.studySession = studySession;
       this.studyMode = studyMode;
       this.isPass = isPass;
       this.mark = mark;
       this.note = note;
       this.isActive = isActive;
       this.studentResitCourse = studentResitCourse;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="StudentCourseID", unique=true, nullable=false)
    public Integer getStudentCourseId() {
        return this.studentCourseId;
    }
    
    public void setStudentCourseId(Integer studentCourseId) {
        this.studentCourseId = studentCourseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CourseID")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentSessionID")
    public StudySession getStudySession() {
        return this.studySession;
    }
    
    public void setStudySession(StudySession studySession) {
        this.studySession = studySession;
    }

    
    @Column(name="StudyMode", length=20)
    public String getStudyMode() {
        return this.studyMode;
    }
    
    public void setStudyMode(String studyMode) {
        this.studyMode = studyMode;
    }

    
    @Column(name="IsPass")
    public Boolean getIsPass() {
        return this.isPass;
    }
    
    public void setIsPass(Boolean isPass) {
        this.isPass = isPass;
    }

    
    @Column(name="Mark", nullable=false, precision=12, scale=0)
    public float getMark() {
        return this.mark;
    }
    
    public void setMark(float mark) {
        this.mark = mark;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="studentCourse")
    public StudentResitCourse getStudentResitCourse() {
        return this.studentResitCourse;
    }
    
    public void setStudentResitCourse(StudentResitCourse studentResitCourse) {
        this.studentResitCourse = studentResitCourse;
    }




}


