package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubjectInLevel generated by hbm2java
 */
@Entity
@Table(name="subject_in_level"
    ,catalog="sfm"
)
public class SubjectInLevel  implements java.io.Serializable {


     private Integer subInLvId;
     private Major major;
     private StudyLevel studyLevel;
     private Subject subject;

    public SubjectInLevel() {
    }

    public SubjectInLevel(Major major, StudyLevel studyLevel, Subject subject) {
       this.major = major;
       this.studyLevel = studyLevel;
       this.subject = subject;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SubInLvID", unique=true, nullable=false)
    public Integer getSubInLvId() {
        return this.subInLvId;
    }
    
    public void setSubInLvId(Integer subInLvId) {
        this.subInLvId = subInLvId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MajorID", nullable=false)
    public Major getMajor() {
        return this.major;
    }
    
    public void setMajor(Major major) {
        this.major = major;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudyLevelID", nullable=false)
    public StudyLevel getStudyLevel() {
        return this.studyLevel;
    }
    
    public void setStudyLevel(StudyLevel studyLevel) {
        this.studyLevel = studyLevel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubjectID", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }




}


