package com.project.fpt.sfm.entities;
// Generated Oct 4, 2015 1:25:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubjectCategory generated by hbm2java
 */
@Entity
@Table(name="subject_category"
    ,catalog="sfm"
)
public class SubjectCategory  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryNameE;
     private String categoryNameV;
     private String note;
     private boolean isActive;
     private Set<Subject> subjects = new HashSet<Subject>(0);

    public SubjectCategory() {
    }

	
    public SubjectCategory(boolean isActive) {
        this.isActive = isActive;
    }
    public SubjectCategory(String categoryNameE, String categoryNameV, String note, boolean isActive, Set<Subject> subjects) {
       this.categoryNameE = categoryNameE;
       this.categoryNameV = categoryNameV;
       this.note = note;
       this.isActive = isActive;
       this.subjects = subjects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CategoryID", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="CategoryNameE", length=45)
    public String getCategoryNameE() {
        return this.categoryNameE;
    }
    
    public void setCategoryNameE(String categoryNameE) {
        this.categoryNameE = categoryNameE;
    }

    
    @Column(name="CategoryNameV", length=45)
    public String getCategoryNameV() {
        return this.categoryNameV;
    }
    
    public void setCategoryNameV(String categoryNameV) {
        this.categoryNameV = categoryNameV;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subjectCategory")
    public Set<Subject> getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }




}


