package com.project.fpt.sfm.entities;
// Generated Oct 5, 2015 2:12:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subtractamount generated by hbm2java
 */
@Entity
@Table(name="subtractamount"
    ,catalog="sfm"
)
public class Subtractamount  implements java.io.Serializable {


     private Integer subtractAmountId;
     private String subtractAmountName;
     private String subtractAmount;
     private Set<SessionTuition> sessionTuitions = new HashSet<SessionTuition>(0);

    public Subtractamount() {
    }

    public Subtractamount(String subtractAmountName, String subtractAmount, Set<SessionTuition> sessionTuitions) {
       this.subtractAmountName = subtractAmountName;
       this.subtractAmount = subtractAmount;
       this.sessionTuitions = sessionTuitions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SubtractAmountID", unique=true, nullable=false)
    public Integer getSubtractAmountId() {
        return this.subtractAmountId;
    }
    
    public void setSubtractAmountId(Integer subtractAmountId) {
        this.subtractAmountId = subtractAmountId;
    }

    
    @Column(name="SubtractAmountName", length=45)
    public String getSubtractAmountName() {
        return this.subtractAmountName;
    }
    
    public void setSubtractAmountName(String subtractAmountName) {
        this.subtractAmountName = subtractAmountName;
    }

    
    @Column(name="SubtractAmount", length=16777215)
    public String getSubtractAmount() {
        return this.subtractAmount;
    }
    
    public void setSubtractAmount(String subtractAmount) {
        this.subtractAmount = subtractAmount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtractamount")
    public Set<SessionTuition> getSessionTuitions() {
        return this.sessionTuitions;
    }
    
    public void setSessionTuitions(Set<SessionTuition> sessionTuitions) {
        this.sessionTuitions = sessionTuitions;
    }




}


