package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubtractTuition generated by hbm2java
 */
@Entity
@Table(name="subtract_tuition"
    ,catalog="sfm"
)
public class SubtractTuition  implements java.io.Serializable {


     private Integer subtractTuitionId;
     private String subtractTuitionName;
     private int subtractTuition;
     private Set<TuitionPayment> tuitionPayments = new HashSet<TuitionPayment>(0);

    public SubtractTuition() {
    }

	
    public SubtractTuition(String subtractTuitionName, int subtractTuition) {
        this.subtractTuitionName = subtractTuitionName;
        this.subtractTuition = subtractTuition;
    }
    public SubtractTuition(String subtractTuitionName, int subtractTuition, Set<TuitionPayment> tuitionPayments) {
       this.subtractTuitionName = subtractTuitionName;
       this.subtractTuition = subtractTuition;
       this.tuitionPayments = tuitionPayments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SubtractTuitionID", unique=true, nullable=false)
    public Integer getSubtractTuitionId() {
        return this.subtractTuitionId;
    }
    
    public void setSubtractTuitionId(Integer subtractTuitionId) {
        this.subtractTuitionId = subtractTuitionId;
    }

    
    @Column(name="SubtractTuitionName", nullable=false, length=45)
    public String getSubtractTuitionName() {
        return this.subtractTuitionName;
    }
    
    public void setSubtractTuitionName(String subtractTuitionName) {
        this.subtractTuitionName = subtractTuitionName;
    }

    
    @Column(name="SubtractTuition", nullable=false)
    public int getSubtractTuition() {
        return this.subtractTuition;
    }
    
    public void setSubtractTuition(int subtractTuition) {
        this.subtractTuition = subtractTuition;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtractTuition")
    public Set<TuitionPayment> getTuitionPayments() {
        return this.tuitionPayments;
    }
    
    public void setTuitionPayments(Set<TuitionPayment> tuitionPayments) {
        this.tuitionPayments = tuitionPayments;
    }




}


