package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TuitionPayment generated by hbm2java
 */
@Entity
@Table(name="tuition_payment"
    ,catalog="sfm"
)
public class TuitionPayment  implements java.io.Serializable {


     private Integer tuitionPaymentId;
     private Semester semester;
     private Student student;
     private SubtractTuition subtractTuition;
     private Tuition tuition;
     private int totalTuition;
     private int actualTuition;
     private int paidTuition;
     private String bank;
     private Date transferDate;
     private String status;
     private String note;
     private boolean isActive;

    public TuitionPayment() {
    }

	
    public TuitionPayment(Semester semester, Student student, SubtractTuition subtractTuition, Tuition tuition, int totalTuition, int actualTuition, int paidTuition, String bank, String status, boolean isActive) {
        this.semester = semester;
        this.student = student;
        this.subtractTuition = subtractTuition;
        this.tuition = tuition;
        this.totalTuition = totalTuition;
        this.actualTuition = actualTuition;
        this.paidTuition = paidTuition;
        this.bank = bank;
        this.status = status;
        this.isActive = isActive;
    }
    public TuitionPayment(Semester semester, Student student, SubtractTuition subtractTuition, Tuition tuition, int totalTuition, int actualTuition, int paidTuition, String bank, Date transferDate, String status, String note, boolean isActive) {
       this.semester = semester;
       this.student = student;
       this.subtractTuition = subtractTuition;
       this.tuition = tuition;
       this.totalTuition = totalTuition;
       this.actualTuition = actualTuition;
       this.paidTuition = paidTuition;
       this.bank = bank;
       this.transferDate = transferDate;
       this.status = status;
       this.note = note;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TuitionPaymentID", unique=true, nullable=false)
    public Integer getTuitionPaymentId() {
        return this.tuitionPaymentId;
    }
    
    public void setTuitionPaymentId(Integer tuitionPaymentId) {
        this.tuitionPaymentId = tuitionPaymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SemesterID", nullable=false)
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubtractTuitionID", nullable=false)
    public SubtractTuition getSubtractTuition() {
        return this.subtractTuition;
    }
    
    public void setSubtractTuition(SubtractTuition subtractTuition) {
        this.subtractTuition = subtractTuition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TuitionID", nullable=false)
    public Tuition getTuition() {
        return this.tuition;
    }
    
    public void setTuition(Tuition tuition) {
        this.tuition = tuition;
    }

    
    @Column(name="TotalTuition", nullable=false)
    public int getTotalTuition() {
        return this.totalTuition;
    }
    
    public void setTotalTuition(int totalTuition) {
        this.totalTuition = totalTuition;
    }

    
    @Column(name="ActualTuition", nullable=false)
    public int getActualTuition() {
        return this.actualTuition;
    }
    
    public void setActualTuition(int actualTuition) {
        this.actualTuition = actualTuition;
    }

    
    @Column(name="PaidTuition", nullable=false)
    public int getPaidTuition() {
        return this.paidTuition;
    }
    
    public void setPaidTuition(int paidTuition) {
        this.paidTuition = paidTuition;
    }

    
    @Column(name="Bank", nullable=false, length=100)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransferDate", length=19)
    public Date getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }

    
    @Column(name="Status", nullable=false, length=30)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


