package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 11:28:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TuitionPlan generated by hbm2java
 */
@Entity
@Table(name="tuition_plan"
    ,catalog="sfm"
)
public class TuitionPlan  implements java.io.Serializable {


     private Integer tuitionPlanId;
     private Student student;
     private String tuitionName;
     private int tuition;
     private String note;
     private boolean isActive;

    public TuitionPlan() {
    }

	
    public TuitionPlan(Student student, String tuitionName, int tuition, boolean isActive) {
        this.student = student;
        this.tuitionName = tuitionName;
        this.tuition = tuition;
        this.isActive = isActive;
    }
    public TuitionPlan(Student student, String tuitionName, int tuition, String note, boolean isActive) {
       this.student = student;
       this.tuitionName = tuitionName;
       this.tuition = tuition;
       this.note = note;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TuitionPlanID", unique=true, nullable=false)
    public Integer getTuitionPlanId() {
        return this.tuitionPlanId;
    }
    
    public void setTuitionPlanId(Integer tuitionPlanId) {
        this.tuitionPlanId = tuitionPlanId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="TuitionName", nullable=false, length=40)
    public String getTuitionName() {
        return this.tuitionName;
    }
    
    public void setTuitionName(String tuitionName) {
        this.tuitionName = tuitionName;
    }

    
    @Column(name="Tuition", nullable=false)
    public int getTuition() {
        return this.tuition;
    }
    
    public void setTuition(int tuition) {
        this.tuition = tuition;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }


    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("TuitionPlan{");
        sb.append("student=").append(student.getFullName());
        sb.append(", tuitionName='").append(tuitionName).append('\'');
        sb.append(", tuition=").append(tuition);
        sb.append('}');
        return sb.toString();
    }
}


