package com.project.fpt.sfm.entities;
// Generated Oct 8, 2015 2:49:22 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tuition generated by hbm2java
 */
@Entity
@Table(name="tuition"
    ,catalog="sfm"
)
public class Tuition  implements java.io.Serializable {


     private Integer tuitionId;
     private String abbreviation;
     private String tuitionName;
     private int tuitionVnd;
     private int tuitionUsa;
     private String note;
     private boolean isActive;
    @JsonIgnore
     private Set<TuitionPayment> tuitionPayments = new HashSet<TuitionPayment>(0);

    public Tuition() {
    }

	
    public Tuition(String abbreviation, String tuitionName, int tuitionVnd, int tuitionUsa, boolean isActive) {
        this.abbreviation = abbreviation;
        this.tuitionName = tuitionName;
        this.tuitionVnd = tuitionVnd;
        this.tuitionUsa = tuitionUsa;
        this.isActive = isActive;
    }
    public Tuition(String abbreviation, String tuitionName, int tuitionVnd, int tuitionUsa, String note, boolean isActive, Set<TuitionPayment> tuitionPayments) {
       this.abbreviation = abbreviation;
       this.tuitionName = tuitionName;
       this.tuitionVnd = tuitionVnd;
       this.tuitionUsa = tuitionUsa;
       this.note = note;
       this.isActive = isActive;
       this.tuitionPayments = tuitionPayments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TuitionID", unique=true, nullable=false)
    public Integer getTuitionId() {
        return this.tuitionId;
    }
    
    public void setTuitionId(Integer tuitionId) {
        this.tuitionId = tuitionId;
    }

    
    @Column(name="Abbreviation", nullable=false, length=15)
    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    
    @Column(name="TuitionName", nullable=false, length=125)
    public String getTuitionName() {
        return this.tuitionName;
    }
    
    public void setTuitionName(String tuitionName) {
        this.tuitionName = tuitionName;
    }

    
    @Column(name="TuitionVND", nullable=false)
    public int getTuitionVnd() {
        return this.tuitionVnd;
    }
    
    public void setTuitionVnd(int tuitionVnd) {
        this.tuitionVnd = tuitionVnd;
    }

    
    @Column(name="TuitionUSA", nullable=false)
    public int getTuitionUsa() {
        return this.tuitionUsa;
    }
    
    public void setTuitionUsa(int tuitionUsa) {
        this.tuitionUsa = tuitionUsa;
    }

    
    @Column(name="Note", length=65535)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tuition")
    public Set<TuitionPayment> getTuitionPayments() {
        return this.tuitionPayments;
    }
    
    public void setTuitionPayments(Set<TuitionPayment> tuitionPayments) {
        this.tuitionPayments = tuitionPayments;
    }




}


