-- MySQL Script generated by MySQL Workbench
-- 10/14/15 08:08:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sfm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sfm` ;

-- -----------------------------------------------------
-- Schema sfm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sfm` DEFAULT CHARACTER SET utf8 ;
USE `sfm` ;

-- -----------------------------------------------------
-- Table `sfm`.`_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`_user` ;

CREATE TABLE IF NOT EXISTS `sfm`.`_user` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(64) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2352
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`clazz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`clazz` ;

CREATE TABLE IF NOT EXISTS `sfm`.`clazz` (
  `ClassID` INT(11) NOT NULL AUTO_INCREMENT,
  `ClassName` VARCHAR(20) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ClassID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`financial_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`financial_type` ;

CREATE TABLE IF NOT EXISTS `sfm`.`financial_type` (
  `FinancialTypeID` INT(11) NOT NULL AUTO_INCREMENT,
  `FinancialTypeName` VARCHAR(45) NOT NULL DEFAULT '-',
  `FinancialRate` INT(11) NOT NULL DEFAULT '0',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FinancialTypeID`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`major` ;

CREATE TABLE IF NOT EXISTS `sfm`.`major` (
  `MajorID` INT(11) NOT NULL AUTO_INCREMENT,
  `MajorCode` VARCHAR(10) NOT NULL DEFAULT '-',
  `MajorName` VARCHAR(45) NOT NULL DEFAULT '-',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MajorID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`student` (
  `StudentID` INT(11) NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(64) NOT NULL,
  `StudentCode` VARCHAR(10) NOT NULL,
  `Gender` BIT(1) NOT NULL,
  `DateOfBirth` TIMESTAMP NULL DEFAULT NULL,
  `Email` VARCHAR(255) NOT NULL DEFAULT '-',
  `SSN` VARCHAR(10) NOT NULL DEFAULT '-',
  `PhoneNumber` VARCHAR(15) NULL DEFAULT '-',
  `Address` TEXT NULL DEFAULT NULL,
  `MajorID` INT(11) NOT NULL COMMENT 'Chuyên Ngành : SE, SB, IA',
  `FinancialTypeID` INT(11) NOT NULL,
  `IsGraduated` BIT(1) NOT NULL DEFAULT b'0',
  `Status` VARCHAR(30) NOT NULL DEFAULT '-' COMMENT 'Đang Học, Bảo Lưu',
  `SubMajor` VARCHAR(45) NOT NULL DEFAULT '-',
  `Term` VARCHAR(10) NOT NULL DEFAULT '-' COMMENT 'K7, K8, K9',
  `NarrowSpecialization` VARCHAR(20) NOT NULL DEFAULT '-' COMMENT 'Chuyên Nghành hẹp :\n-Normal\n-IS\n-JS\n- ES',
  `ParentPhone` VARCHAR(15) NULL DEFAULT '-',
  `ParentEmail` VARCHAR(255) NULL DEFAULT '-',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `CurrentStudyStage` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`StudentID`),
  UNIQUE INDEX `StudentCode_UNIQUE` (`StudentCode` ASC),
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC),
  INDEX `fk_student_major_idx` (`MajorID` ASC),
  INDEX `fk_student_financial_idx` (`FinancialTypeID` ASC),
  INDEX `fk_student_status_idx` (`Status` ASC),
  CONSTRAINT `fk_student_financial`
    FOREIGN KEY (`FinancialTypeID`)
    REFERENCES `sfm`.`financial_type` (`FinancialTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_major`
    FOREIGN KEY (`MajorID`)
    REFERENCES `sfm`.`major` (`MajorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_user`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2352
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`study_stage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`study_stage` ;

CREATE TABLE IF NOT EXISTS `sfm`.`study_stage` (
  `StudyStageID` INT(11) NOT NULL AUTO_INCREMENT,
  `StageCode` VARCHAR(15) NOT NULL,
  `StageName` VARCHAR(45) NOT NULL,
  `Order` INT(11) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`StudyStageID`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`term`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`term` ;

CREATE TABLE IF NOT EXISTS `sfm`.`term` (
  `TermID` INT(11) NOT NULL AUTO_INCREMENT,
  `TermName` VARCHAR(45) NOT NULL,
  `StartDate` TIMESTAMP NULL DEFAULT NULL,
  `EndDate` TIMESTAMP NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NOT NULL DEFAULT '1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `IsCurrent` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`TermID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`semester` ;

CREATE TABLE IF NOT EXISTS `sfm`.`semester` (
  `SemesterID` INT(11) NOT NULL AUTO_INCREMENT,
  `TermID` INT(11) NOT NULL,
  `MajorID` INT(11) NOT NULL,
  `StudyStageID` INT(11) NOT NULL,
  `StageTuitionUSD` INT(11) NOT NULL DEFAULT '0',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  `DateCreated` TIMESTAMP NULL DEFAULT NULL,
  `DateUpdated` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`SemesterID`),
  INDEX `fk_semester_level_idx` (`StudyStageID` ASC),
  INDEX `fk_semester_season` (`TermID` ASC),
  INDEX `fk_semester_major_idx` (`MajorID` ASC),
  CONSTRAINT `fk_semester_level`
    FOREIGN KEY (`StudyStageID`)
    REFERENCES `sfm`.`study_stage` (`StudyStageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semester_major`
    FOREIGN KEY (`MajorID`)
    REFERENCES `sfm`.`major` (`MajorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semester_season`
    FOREIGN KEY (`TermID`)
    REFERENCES `sfm`.`term` (`TermID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`subject` ;

CREATE TABLE IF NOT EXISTS `sfm`.`subject` (
  `SubjectID` INT(11) NOT NULL AUTO_INCREMENT,
  `SubjectNameE` VARCHAR(80) NULL DEFAULT '-',
  `SubjectNameV` VARCHAR(80) NULL DEFAULT '-',
  `SubjectCode` VARCHAR(15) NULL DEFAULT '-',
  `Abbreviation` VARCHAR(15) NULL DEFAULT '-',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SubjectID`))
ENGINE = InnoDB
AUTO_INCREMENT = 137
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`subject_in_semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`subject_in_semester` ;

CREATE TABLE IF NOT EXISTS `sfm`.`subject_in_semester` (
  `SubInSemID` INT(11) NOT NULL AUTO_INCREMENT,
  `SubjectID` INT(11) NOT NULL,
  `SemesterID` INT(11) NOT NULL,
  `NumberOfCredit` INT(11) NOT NULL DEFAULT '3',
  `Half` INT(11) NOT NULL DEFAULT '1',
  `StartDate` TIMESTAMP NULL DEFAULT NULL,
  `EndDate` TIMESTAMP NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SubInSemID`),
  INDEX `fk_sub_sem_idx` (`SubjectID` ASC),
  INDEX `fk_sem_sub_idx` (`SemesterID` ASC),
  CONSTRAINT `fk_sem_sub`
    FOREIGN KEY (`SemesterID`)
    REFERENCES `sfm`.`semester` (`SemesterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_sem`
    FOREIGN KEY (`SubjectID`)
    REFERENCES `sfm`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 285
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`course` ;

CREATE TABLE IF NOT EXISTS `sfm`.`course` (
  `CourseID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `SubInSemID` INT(11) NOT NULL,
  `ClassID` INT(11) NOT NULL,
  `Mark` FLOAT NOT NULL DEFAULT '0',
  `IsPass` BIT(1) NOT NULL DEFAULT b'0',
  `IsRetake` BIT(1) NOT NULL DEFAULT b'0',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CourseID`),
  INDEX `fk_course_student_idx` (`StudentID` ASC),
  INDEX `fk_course_subject_idx` (`SubInSemID` ASC),
  INDEX `fk_course_class_idx` (`ClassID` ASC),
  CONSTRAINT `fk_course_class`
    FOREIGN KEY (`ClassID`)
    REFERENCES `sfm`.`clazz` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_subject`
    FOREIGN KEY (`SubInSemID`)
    REFERENCES `sfm`.`subject_in_semester` (`SubInSemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`credit_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`credit_student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`credit_student` (
  `StudentID` INT(11) NOT NULL AUTO_INCREMENT,
  `CreditRate` INT(11) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_loans_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`credit_debt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`credit_debt` ;

CREATE TABLE IF NOT EXISTS `sfm`.`credit_debt` (
  `CreditDebtID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `InterestRate` INT(11) NULL DEFAULT NULL,
  `BaseMoney` MEDIUMTEXT NOT NULL,
  `Interest` MEDIUMTEXT NOT NULL,
  `TotalInterest` MEDIUMTEXT NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CreditDebtID`),
  INDEX `fk_interest_before_idx` (`StudentID` ASC),
  CONSTRAINT `fk_interest_before`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`credit_student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`investment_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`investment_student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`investment_student` (
  `StudentID` INT(11) NOT NULL,
  `InvestmentRate` INT(11) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_investing_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`investment_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`investment_report` ;

CREATE TABLE IF NOT EXISTS `sfm`.`investment_report` (
  `ReportID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `TotalMoney` MEDIUMTEXT NOT NULL,
  `PaidMoney` MEDIUMTEXT NOT NULL,
  `PayStatus` BIT(1) NOT NULL,
  `Bank` VARCHAR(45) NULL DEFAULT NULL,
  `DateTransfer` TIMESTAMP NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ReportID`),
  INDEX `fk_investing_report_idx` (`StudentID` ASC),
  CONSTRAINT `fk_investing_report`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`investment_student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`manager` ;

CREATE TABLE IF NOT EXISTS `sfm`.`manager` (
  `ManagerID` INT(11) NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ManagerID`),
  CONSTRAINT `fk_manager_user`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`mandatory_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`mandatory_subject` ;

CREATE TABLE IF NOT EXISTS `sfm`.`mandatory_subject` (
  `MandatorySubID` INT(11) NOT NULL AUTO_INCREMENT,
  `SubjectId` INT(11) NOT NULL,
  `RequireSubjectID` INT(11) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MandatorySubID`),
  INDEX `fk_subject_has_subject_subject2_idx` (`RequireSubjectID` ASC),
  INDEX `fk_subject_has_subject_subject1_idx` (`SubjectId` ASC),
  CONSTRAINT `fk_subject_has_subject_subject1`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `sfm`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_has_subject_subject2`
    FOREIGN KEY (`RequireSubjectID`)
    REFERENCES `sfm`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`money_rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`money_rate` ;

CREATE TABLE IF NOT EXISTS `sfm`.`money_rate` (
  `RateID` INT(11) NOT NULL AUTO_INCREMENT,
  `Rate` FLOAT NOT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RateID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`retake_subject_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`retake_subject_payment` ;

CREATE TABLE IF NOT EXISTS `sfm`.`retake_subject_payment` (
  `RetakeSubPaymentID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `SubInSemID` INT(11) NOT NULL,
  `TotalTuition` INT(11) NOT NULL DEFAULT '0',
  `PaidTuition` INT(11) NOT NULL DEFAULT '0',
  `Status` BIT(1) NOT NULL DEFAULT b'0',
  `TransferDate` TIMESTAMP NULL DEFAULT NULL,
  `Bank` VARCHAR(125) NOT NULL DEFAULT '-',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RetakeSubPaymentID`),
  INDEX `fk_retake_sub_student_idx` (`StudentID` ASC),
  INDEX `fk_retake_sub_in_sem_idx` (`SubInSemID` ASC),
  CONSTRAINT `fk_retake_sub_in_sem`
    FOREIGN KEY (`SubInSemID`)
    REFERENCES `sfm`.`subject_in_semester` (`SubInSemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retake_sub_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`role` ;

CREATE TABLE IF NOT EXISTS `sfm`.`role` (
  `RoleID` INT(11) NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(30) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`staff` ;

CREATE TABLE IF NOT EXISTS `sfm`.`staff` (
  `StaffID` INT(11) NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`StaffID`),
  CONSTRAINT `fk_staff_user`
    FOREIGN KEY (`StaffID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`student_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`student_status` ;

CREATE TABLE IF NOT EXISTS `sfm`.`student_status` (
  `StudentStatusID` INT(11) NOT NULL AUTO_INCREMENT,
  `StatusName` VARCHAR(45) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`StudentStatusID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`subtract_tuition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`subtract_tuition` ;

CREATE TABLE IF NOT EXISTS `sfm`.`subtract_tuition` (
  `SubtractTuitionID` INT(11) NOT NULL AUTO_INCREMENT,
  `SubtractTuitionName` VARCHAR(45) NOT NULL DEFAULT '-',
  `SubtractTuition` INT(11) NOT NULL DEFAULT '0',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SubtractTuitionID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`system_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`system_config` ;

CREATE TABLE IF NOT EXISTS `sfm`.`system_config` (
  `Key` VARCHAR(40) NOT NULL,
  `Value` VARCHAR(125) NOT NULL,
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`tuition_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`tuition_payment` ;

CREATE TABLE IF NOT EXISTS `sfm`.`tuition_payment` (
  `TuitionPaymentID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `SemesterID` INT(11) NOT NULL,
  `TotalTuition` INT(11) NOT NULL DEFAULT '0',
  `SubtractTuitionID` INT(11) NULL DEFAULT NULL COMMENT 'Cac khoan khau tru',
  `PaidTuition` INT(11) NOT NULL DEFAULT '0',
  `Bank` VARCHAR(100) NOT NULL DEFAULT '-',
  `TransferDate` TIMESTAMP NULL DEFAULT NULL,
  `Status` BIT(1) NOT NULL DEFAULT b'0',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TuitionPaymentID`),
  INDEX `fk_subtract_amount_idx` (`SubtractTuitionID` ASC),
  INDEX `fk_payment_student_idx` (`StudentID` ASC),
  INDEX `fk_payment_semester_idx` (`SemesterID` ASC),
  CONSTRAINT `fk_payment_semester`
    FOREIGN KEY (`SemesterID`)
    REFERENCES `sfm`.`semester` (`SemesterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subtract_amount`
    FOREIGN KEY (`SubtractTuitionID`)
    REFERENCES `sfm`.`subtract_tuition` (`SubtractTuitionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`tuition_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`tuition_plan` ;

CREATE TABLE IF NOT EXISTS `sfm`.`tuition_plan` (
  `TuitionPlanID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `TermID` INT(11) NOT NULL,
  `TuitionName` VARCHAR(64) NOT NULL DEFAULT '-',
  `Tuition` INT(11) NOT NULL DEFAULT '0',
  `TuitionType` VARCHAR(125) NULL DEFAULT NULL,
  PRIMARY KEY (`TuitionPlanID`),
  INDEX `fk_plan_student_idx` (`StudentID` ASC),
  INDEX `fk_plan_term_idx` (`TermID` ASC),
  CONSTRAINT `fk_plan_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_term`
    FOREIGN KEY (`TermID`)
    REFERENCES `sfm`.`term` (`TermID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`user_role` ;

CREATE TABLE IF NOT EXISTS `sfm`.`user_role` (
  `UserRoleID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserID` INT(11) NOT NULL,
  `RoleID` INT(11) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'1',
  `Date_Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserRoleID`),
  INDEX `fk__User_has_Role_Role1_idx` (`RoleID` ASC),
  INDEX `fk__User_has_Role__User1_idx` (`UserID` ASC),
  CONSTRAINT `fk__User_has_Role_Role1`
    FOREIGN KEY (`RoleID`)
    REFERENCES `sfm`.`role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__User_has_Role__User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
