-- MySQL Script generated by MySQL Workbench
-- 10/06/15 16:53:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sfm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sfm` ;

-- -----------------------------------------------------
-- Schema sfm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sfm` DEFAULT CHARACTER SET utf8 ;
USE `sfm` ;

-- -----------------------------------------------------
-- Table `sfm`.`_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`_user` ;

CREATE TABLE IF NOT EXISTS `sfm`.`_user` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(64) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`clazz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`clazz` ;

CREATE TABLE IF NOT EXISTS `sfm`.`clazz` (
  `ClassID` INT(11) NOT NULL AUTO_INCREMENT,
  `ClassName` VARCHAR(45) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL,
  PRIMARY KEY (`ClassID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`subject_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`subject_category` ;

CREATE TABLE IF NOT EXISTS `sfm`.`subject_category` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryNameE` VARCHAR(45) NULL DEFAULT '-',
  `CategoryNameV` VARCHAR(45) NULL DEFAULT '-',
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`subject` ;

CREATE TABLE IF NOT EXISTS `sfm`.`subject` (
  `SubjectID` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryID` INT(11) NOT NULL,
  `SubjectNameE` VARCHAR(80) NULL DEFAULT '-',
  `SubjectNameV` VARCHAR(80) NULL DEFAULT '-',
  `SubjectCode` VARCHAR(15) NULL DEFAULT '-',
  `Abbreviation` VARCHAR(15) NULL DEFAULT '-',
  `NumOfCredit` INT(11) NULL DEFAULT 3,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`SubjectID`),
  INDEX `fk_subject_category_idx` (`CategoryID` ASC),
  CONSTRAINT `fk_subject_category`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `sfm`.`subject_category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`compulsory_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`compulsory_subject` ;

CREATE TABLE IF NOT EXISTS `sfm`.`compulsory_subject` (
  `compulsorySubjectID` INT(11) NOT NULL,
  `subjectID` INT(11) NOT NULL,
  PRIMARY KEY (`compulsorySubjectID`, `subjectID`),
  INDEX `fk_subject_2_idx` (`compulsorySubjectID` ASC),
  INDEX `fk_subject_1` (`subjectID` ASC),
  CONSTRAINT `fk_subject_1`
    FOREIGN KEY (`subjectID`)
    REFERENCES `sfm`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_2`
    FOREIGN KEY (`compulsorySubjectID`)
    REFERENCES `sfm`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`student` (
  `StudentID` INT(11) NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(64) NOT NULL,
  `StudentCode` VARCHAR(10) NOT NULL,
  `Gender` BIT(1) NULL DEFAULT NULL,
  `DateOfBirth` TIMESTAMP NULL,
  `Email` VARCHAR(255) NULL DEFAULT '-',
  `SSN` VARCHAR(10) NULL DEFAULT '-',
  `PhoneNumber` VARCHAR(15) NULL DEFAULT '-',
  `Address` TEXT NULL DEFAULT NULL,
  `FinanceType` VARCHAR(15) NULL DEFAULT '-' COMMENT 'HB, TD, ĐT, BT',
  `Major` VARCHAR(15) NULL DEFAULT '-' COMMENT 'Chuyên Ngành : SE, SB, IA',
  `IsGraduated` BIT(1) NULL DEFAULT 0,
  `StudyStatus` VARCHAR(30) NULL DEFAULT '-' COMMENT 'Đang Học, Bảo Lưu',
  `SubMajor` VARCHAR(45) NULL DEFAULT '-',
  `Term` VARCHAR(10) NULL DEFAULT '-' COMMENT 'K7, K8, K9',
  `NarrowSpecialization` VARCHAR(20) NULL DEFAULT '-' COMMENT 'Chuyên Nghành hẹp :\n-Normal\n-IS\n-JS\n- ES',
  `ParentPhone` VARCHAR(15) NULL DEFAULT '-',
  `ParentEmail` VARCHAR(255) NULL DEFAULT '-',
  PRIMARY KEY (`StudentID`),
  UNIQUE INDEX `StudentCode_UNIQUE` (`StudentCode` ASC),
  CONSTRAINT `fk_student_user`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`session` ;

CREATE TABLE IF NOT EXISTS `sfm`.`session` (
  `SessionID` INT(11) NOT NULL AUTO_INCREMENT,
  `SessionCode` VARCHAR(15) NULL DEFAULT '-',
  `SessionName` VARCHAR(45) NULL DEFAULT '-',
  `TuitionUSA` INT NULL DEFAULT 0,
  `TuitionVND` INT NULL DEFAULT 0,
  `Note` TEXT NULL DEFAULT NULL COMMENT 'Bắt buộc\nTheo mức học thực tế\nĐối với riêng ngành ngôn ngữ\n',
  `IsActive` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`SessionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`semester` ;

CREATE TABLE IF NOT EXISTS `sfm`.`semester` (
  `SemesterID` INT(11) NOT NULL AUTO_INCREMENT,
  `SemesterName` VARCHAR(45) NULL DEFAULT '-',
  `StartDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`SemesterID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`study_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`study_session` ;

CREATE TABLE IF NOT EXISTS `sfm`.`study_session` (
  `StudySessionID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `SessionID` INT(11) NOT NULL,
  `SemesterID` INT(11) NOT NULL,
  PRIMARY KEY (`StudySessionID`),
  INDEX `fk_study_progress_2_idx` (`SessionID` ASC),
  INDEX `fk_study_session3_idx` (`SemesterID` ASC),
  INDEX `fk_study_progress_1` (`StudentID` ASC),
  CONSTRAINT `fk_study_progress_1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_study_progress_2`
    FOREIGN KEY (`SessionID`)
    REFERENCES `sfm`.`session` (`SessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_study_session3`
    FOREIGN KEY (`SemesterID`)
    REFERENCES `sfm`.`semester` (`SemesterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`course` ;

CREATE TABLE IF NOT EXISTS `sfm`.`course` (
  `CourseID` INT(11) NOT NULL AUTO_INCREMENT,
  `SubjectID` INT(11) NOT NULL,
  `StudySessionID` INT NOT NULL,
  `Class` VARCHAR(30) NULL DEFAULT '-',
  `Haft` INT(11) NULL DEFAULT 1,
  `StartDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT 1,
  `Mark` FLOAT NULL DEFAULT -1,
  `IsPass` BIT NULL,
  `CourseStatus` VARCHAR(30) NULL DEFAULT '-' COMMENT 'Bắt đầu, đang học, đã đóng',
  PRIMARY KEY (`CourseID`),
  INDEX `fk_course_study_session_idx` (`StudySessionID` ASC),
  INDEX `fk_course_subject_idx` (`SubjectID` ASC),
  CONSTRAINT `fk_course_study_session`
    FOREIGN KEY (`StudySessionID`)
    REFERENCES `sfm`.`study_session` (`StudySessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_subject`
    FOREIGN KEY (`SubjectID`)
    REFERENCES `sfm`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`investing_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`investing_student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`investing_student` (
  `StudentID` INT(11) NOT NULL,
  `InvestingRate` INT(11) NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_investing_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`investing_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`investing_report` ;

CREATE TABLE IF NOT EXISTS `sfm`.`investing_report` (
  `ReportID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `TotalMoney` MEDIUMTEXT NOT NULL,
  `PaidMoney` MEDIUMTEXT NOT NULL,
  `PayStatus` BIT(1) NOT NULL,
  `Bank` VARCHAR(45) NULL DEFAULT NULL,
  `DateTransfer` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ReportID`),
  INDEX `fk_investing_report_idx` (`StudentID` ASC),
  CONSTRAINT `fk_investing_report`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`investing_student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`loans_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`loans_student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`loans_student` (
  `StudentID` INT(11) NOT NULL AUTO_INCREMENT,
  `LoansRate` INT(11) NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_loans_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`loans_interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`loans_interest` ;

CREATE TABLE IF NOT EXISTS `sfm`.`loans_interest` (
  `ReportID` INT(11) NOT NULL AUTO_INCREMENT,
  `StudentID` INT(11) NOT NULL,
  `InterestRate` INT(11) NULL DEFAULT NULL,
  `BaseMoney` MEDIUMTEXT NOT NULL,
  `Interest` MEDIUMTEXT NOT NULL,
  `TotalInterest` MEDIUMTEXT NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL,
  PRIMARY KEY (`ReportID`),
  INDEX `fk_interest_before_idx` (`StudentID` ASC),
  CONSTRAINT `fk_interest_before`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`loans_student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`manager` ;

CREATE TABLE IF NOT EXISTS `sfm`.`manager` (
  `ManagerID` INT(11) NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ManagerID`),
  CONSTRAINT `fk_manager_user`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`role` ;

CREATE TABLE IF NOT EXISTS `sfm`.`role` (
  `RoleID` INT(11) NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`scholarship_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`scholarship_student` ;

CREATE TABLE IF NOT EXISTS `sfm`.`scholarship_student` (
  `StudentID` INT(11) NOT NULL,
  `ScholarshipRate` INT(11) NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_schoolarship_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`subtract_tuition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`subtract_tuition` ;

CREATE TABLE IF NOT EXISTS `sfm`.`subtract_tuition` (
  `SubtractTuitionID` INT(11) NOT NULL AUTO_INCREMENT,
  `SubtractTuitionName` VARCHAR(45) NULL DEFAULT '-',
  `SubtractAmount` INT NULL DEFAULT 0,
  PRIMARY KEY (`SubtractTuitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`session_tuition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`session_tuition` ;

CREATE TABLE IF NOT EXISTS `sfm`.`session_tuition` (
  `SessionTuitionID` INT(11) NOT NULL AUTO_INCREMENT,
  `TotalTuition` INT NULL DEFAULT 0,
  `SubtractTuitionID` INT(11) NOT NULL DEFAULT -1 COMMENT 'Cac khoan khau tru',
  `ActualTuition` INT NULL DEFAULT 0,
  `PaidTuition` INT NULL DEFAULT 0,
  `Bank` VARCHAR(100) NULL DEFAULT '-',
  `TransferDate` TIMESTAMP NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT 0,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`SessionTuitionID`),
  INDEX `fk_subtract_amount_idx` (`SubtractTuitionID` ASC),
  CONSTRAINT `fk_session_tuition`
    FOREIGN KEY (`SessionTuitionID`)
    REFERENCES `sfm`.`study_session` (`StudySessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subtract_amount`
    FOREIGN KEY (`SubtractTuitionID`)
    REFERENCES `sfm`.`subtract_tuition` (`SubtractTuitionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`staff` ;

CREATE TABLE IF NOT EXISTS `sfm`.`staff` (
  `StaffID` INT(11) NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`StaffID`),
  CONSTRAINT `fk_staff_user`
    FOREIGN KEY (`StaffID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`student_resit_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`student_resit_course` ;

CREATE TABLE IF NOT EXISTS `sfm`.`student_resit_course` (
  `StudentCourseID` INT(11) NOT NULL,
  `TotalMoney` MEDIUMTEXT NOT NULL,
  `MustPayMoney` MEDIUMTEXT NOT NULL,
  `PaidMoney` MEDIUMTEXT NOT NULL,
  `PayStatus` BIT(1) NOT NULL,
  `Note` TEXT NULL DEFAULT NULL,
  `IsActive` BIT(1) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sfm`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm`.`user_role` ;

CREATE TABLE IF NOT EXISTS `sfm`.`user_role` (
  `UserID` INT(11) NOT NULL,
  `RoleID` INT(11) NOT NULL,
  PRIMARY KEY (`UserID`, `RoleID`),
  INDEX `fk__User_has_Role_Role1_idx` (`RoleID` ASC),
  INDEX `fk__User_has_Role__User1_idx` (`UserID` ASC),
  CONSTRAINT `fk__User_has_Role_Role1`
    FOREIGN KEY (`RoleID`)
    REFERENCES `sfm`.`role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__User_has_Role__User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `sfm`.`_user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
