-- MySQL Script generated by MySQL Workbench
-- 10/03/15 18:40:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sfm_for_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sfm_for_test` ;

-- -----------------------------------------------------
-- Schema sfm_for_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sfm_for_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sfm_for_test` ;

-- -----------------------------------------------------
-- Table `sfm_for_test`.`System_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`System_User` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`System_User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(64) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `RoleID` INT NOT NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Staff` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Staff` (
  `StaffID` INT NOT NULL AUTO_INCREMENT,
  `Fullname` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(15) NULL,
  `Address` VARCHAR(255) NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`StaffID`),
  CONSTRAINT `fk_staff_user`
    FOREIGN KEY (`StaffID`)
    REFERENCES `sfm_for_test`.`System_User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Manager` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Manager` (
  `ManagerID` INT NOT NULL AUTO_INCREMENT,
  `Fullname` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(15) NULL,
  `Address` VARCHAR(255) NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`ManagerID`),
  CONSTRAINT `fk_manager_user`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `sfm_for_test`.`System_User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Student` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Student` (
  `StudenID` INT NOT NULL AUTO_INCREMENT,
  `Major` VARCHAR(5) NOT NULL COMMENT 'Chuyên Ngành : SE, SB, IA',
  `StudyStatus` VARCHAR(15) NOT NULL COMMENT 'Đang Học, Bảo Lưu',
  `Term` VARCHAR(10) NOT NULL COMMENT 'K7, K8, K9',
  `Special` VARCHAR(10) NOT NULL COMMENT 'Chuyên Nghành hẹp :\n-Normal\n-IS\n-JS\n- ES',
  `Fullname` VARCHAR(64) NOT NULL,
  `DateOfBirth` TIMESTAMP NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `StudentCode` VARCHAR(10) NOT NULL,
  `Gender` BIT NOT NULL,
  `ParentPhone` VARCHAR(15) NULL,
  `ParentEmail` VARCHAR(255) NULL,
  `IsGraduated` BIT NOT NULL,
  `SSN` VARCHAR(10) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `Address` TEXT NULL,
  PRIMARY KEY (`StudenID`),
  UNIQUE INDEX `StudentCode_UNIQUE` (`StudentCode` ASC),
  CONSTRAINT `fk_student_user`
    FOREIGN KEY (`StudenID`)
    REFERENCES `sfm_for_test`.`System_User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Subject_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Subject_Category` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Subject_Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryNameE` VARCHAR(45) NULL,
  `CategoryNameV` VARCHAR(45) NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Subject` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Subject` (
  `SubjectID` INT NOT NULL AUTO_INCREMENT,
  `CategoryID` INT NOT NULL,
  `SubjectNameE` VARCHAR(45) NULL,
  `SubjectNameV` VARCHAR(45) NULL,
  `SubjectCode` VARCHAR(10) NOT NULL,
  `NumOfCredit` INT NOT NULL,
  `Type` VARCHAR(20) NOT NULL COMMENT 'Bắt buộc\nChuyên Ngành JS\nChuyên Ngành IS',
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  `NumOfLesson` INT NOT NULL,
  PRIMARY KEY (`SubjectID`),
  INDEX `fk_subject_category_idx` (`CategoryID` ASC),
  CONSTRAINT `fk_subject_category`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `sfm_for_test`.`Subject_Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Clazz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Clazz` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Clazz` (
  `ClassID` INT NOT NULL AUTO_INCREMENT,
  `ClassName` VARCHAR(45) NOT NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`ClassID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Session` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Session` (
  `ProgressID` INT NOT NULL AUTO_INCREMENT,
  `ProgressNameE` VARCHAR(45) NOT NULL,
  `ProgressNameV` VARCHAR(45) NOT NULL,
  `TutitionUSA` MEDIUMTEXT NOT NULL,
  `TutitionVND` MEDIUMTEXT NOT NULL,
  `Note` TEXT NOT NULL COMMENT 'Bắt buộc\nTheo mức học thực tế\nĐối với riêng ngành ngôn ngữ\n',
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`ProgressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Semester` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Semester` (
  `SemesterID` INT NOT NULL AUTO_INCREMENT,
  `SemesterName` VARCHAR(45) NOT NULL,
  `StartDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`SemesterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Course` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Course` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `SubjectID` INT NOT NULL,
  `ClassID` INT NOT NULL,
  `Haft` INT NOT NULL,
  `StartDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  `CourseStatus` VARCHAR(20) NULL COMMENT 'Chưa Bắt đầu\nĐang Bắt đầu\nĐóng',
  PRIMARY KEY (`CourseID`),
  INDEX `fk_course_class_idx` (`ClassID` ASC),
  INDEX `fk_course_subject_idx` (`SubjectID` ASC),
  CONSTRAINT `fk_course_class`
    FOREIGN KEY (`ClassID`)
    REFERENCES `sfm_for_test`.`Clazz` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_subject`
    FOREIGN KEY (`SubjectID`)
    REFERENCES `sfm_for_test`.`Subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Study_Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Study_Session` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Study_Session` (
  `SessionID` INT NOT NULL,
  `StudentID` INT NOT NULL,
  `ProgressID` INT NOT NULL,
  `SemesterID` INT NOT NULL,
  PRIMARY KEY (`SessionID`),
  INDEX `fk_study_progress_2_idx` (`ProgressID` ASC),
  INDEX `fk_study_session3_idx` (`SemesterID` ASC),
  CONSTRAINT `fk_study_progress_1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm_for_test`.`Student` (`StudenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_study_progress_2`
    FOREIGN KEY (`ProgressID`)
    REFERENCES `sfm_for_test`.`Session` (`ProgressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_study_session3`
    FOREIGN KEY (`SemesterID`)
    REFERENCES `sfm_for_test`.`Semester` (`SemesterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Student_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Student_Course` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Student_Course` (
  `StudentCourseID` INT NOT NULL AUTO_INCREMENT,
  `StudentSessionID` INT NULL,
  `CourseID` INT NULL,
  `StudyMode` VARCHAR(20) NULL COMMENT 'Hoc Lai\nHoc Cai Thien',
  `IsPass` BIT NULL,
  `Mark` FLOAT NOT NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`StudentCourseID`),
  INDEX `fk_stucourse_course_idx` (`CourseID` ASC),
  INDEX `fk_course_student_idx` (`StudentSessionID` ASC),
  CONSTRAINT `fk_course_student`
    FOREIGN KEY (`StudentSessionID`)
    REFERENCES `sfm_for_test`.`Study_Session` (`SessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stucourse_course`
    FOREIGN KEY (`CourseID`)
    REFERENCES `sfm_for_test`.`Course` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Session_Tutition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Session_Tutition` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Session_Tutition` (
  `SessionID` INT NOT NULL AUTO_INCREMENT,
  `TotalMoney` MEDIUMTEXT NOT NULL,
  `SubtractMoney` MEDIUMTEXT NOT NULL COMMENT 'Cac khoan khau tru',
  `RealPayMoney` MEDIUMTEXT NOT NULL,
  `PaidMoney` MEDIUMTEXT NOT NULL,
  `Bank` VARCHAR(45) NULL,
  `TransferDate` TIMESTAMP NULL,
  `IsPaidFull` BIT NOT NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`SessionID`),
  CONSTRAINT `fk_session_tuition`
    FOREIGN KEY (`SessionID`)
    REFERENCES `sfm_for_test`.`Study_Session` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Loans_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Loans_Student` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Loans_Student` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `LoansRate` INT NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_loans_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm_for_test`.`Student` (`StudenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Loans_Interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Loans_Interest` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Loans_Interest` (
  `ReportID` INT NOT NULL AUTO_INCREMENT,
  `StudentID` INT NOT NULL,
  `InterestRate` INT NULL,
  `BaseMoney` MEDIUMTEXT NOT NULL,
  `Interest` MEDIUMTEXT NOT NULL,
  `TotalInterest` MEDIUMTEXT NOT NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`ReportID`),
  INDEX `fk_interest_before_idx` (`StudentID` ASC),
  CONSTRAINT `fk_interest_before`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm_for_test`.`Loans_Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Scholarship_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Scholarship_Student` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Scholarship_Student` (
  `StudentID` INT NOT NULL,
  `ScholarshipRate` INT NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_schoolarship_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm_for_test`.`Student` (`StudenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Investing_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Investing_Student` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Investing_Student` (
  `StudentID` INT NOT NULL,
  `InvestingRate` INT NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_investing_student`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm_for_test`.`Student` (`StudenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Investing_Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Investing_Report` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Investing_Report` (
  `ReportID` INT NOT NULL AUTO_INCREMENT,
  `StudentID` INT NOT NULL,
  `TotalMoney` MEDIUMTEXT NOT NULL,
  `PaidMoney` MEDIUMTEXT NOT NULL,
  `PayStatus` BIT NOT NULL,
  `Bank` VARCHAR(45) NULL,
  `DateTransfer` TIMESTAMP NULL,
  PRIMARY KEY (`ReportID`),
  INDEX `fk_investing_report_idx` (`StudentID` ASC),
  CONSTRAINT `fk_investing_report`
    FOREIGN KEY (`StudentID`)
    REFERENCES `sfm_for_test`.`Investing_Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Student_Resit_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Student_Resit_Course` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Student_Resit_Course` (
  `StudentCourseID` INT NOT NULL,
  `TotalMoney` MEDIUMTEXT NOT NULL,
  `MustPayMoney` MEDIUMTEXT NOT NULL,
  `PaidMoney` MEDIUMTEXT NOT NULL,
  `PayStatus` BIT NOT NULL,
  `Note` TEXT NULL,
  `IsActive` BIT NOT NULL,
  PRIMARY KEY (`StudentCourseID`),
  CONSTRAINT `fk_resit_student_course`
    FOREIGN KEY (`StudentCourseID`)
    REFERENCES `sfm_for_test`.`Student_Course` (`StudentCourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sfm_for_test`.`Compulsory_Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sfm_for_test`.`Compulsory_Subject` ;

CREATE TABLE IF NOT EXISTS `sfm_for_test`.`Compulsory_Subject` (
  `compulsorySubjectID` INT NOT NULL,
  `subjectID` INT NOT NULL,
  PRIMARY KEY (`compulsorySubjectID`, `subjectID`),
  INDEX `fk_subject_2_idx` (`compulsorySubjectID` ASC),
  CONSTRAINT `fk_subject_1`
    FOREIGN KEY (`subjectID`)
    REFERENCES `sfm_for_test`.`Subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_2`
    FOREIGN KEY (`compulsorySubjectID`)
    REFERENCES `sfm_for_test`.`Subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
